### ISSUE TITLE
Fix Octokit deprecation

### ISSUE THREAD

**Issue by marekdedic** [skaut/wordpress-version-checker#44]
```
{ Deprecation: [@octokit/rest] "result.data.repositories" is deprecated. Use "result.data" instead

    at Array.get (/rbd/pnpm-volume/a766a15d-3d6a-476b-a6ec-21fc8beaa1f0/node_modules/.registry.npmjs.org/@octokit/rest/16.30.1/node_modules/@octokit/rest/plugins/pagination/normalize-paginated-list-response.js:66:9)

    at github.paginate.response (/rbd/pnpm-volume/a766a15d-3d6a-476b-a6ec-21fc8beaa1f0/node_modules/.registry.npmjs.org/probot-scheduler/2.0.0-beta.1/node_modules/probot-scheduler/index.js:99:30)

    at iterator.next.then.result (/rbd/pnpm-volume/a766a15d-3d6a-476b-a6ec-21fc8beaa1f0/node_modules/.registry.npmjs.org/@octokit/rest/16.30.1/node_modules/@octokit/rest/plugins/pagination/paginate.js:31:15) name: 'Deprecation' }
```

**Comment by marekdedic** [comment]
Library issue.
